/* =====================================================================
   VIEW: التقارير والتحليل — كل المؤشرات بتعريف معلن + تصدير
   ===================================================================== */
(function (root) {
  'use strict';
  var D = root.DOM, h = D.h, U = root.U, S = root.STORE, UI = root.UI, t = root.t, L = root.LOOKUPS, R = root.REPORTS, STAGES = root.STAGES, MODEL = root.MODEL, ENGINE = root.ENGINE;
  root.VIEWS = root.VIEWS || {};
  var state = { period: 'this_year', from: '', to: '' };

  root.VIEWS.reports = {
    render: function (main) {
      var db = S.db, canCom = S.can('commercial.view');
      var range = state.period === 'custom' ? { from: state.from, to: state.to } : U.periodRange(state.period);
      main.appendChild(h('div', { class: 'page-head' }, h('div', null, h('h1', null, t('rp.title')), h('p', { class: 'sub' }, t('rp.sub')))));
      var per = h('select', { class: 'sel', 'aria-label': t('app.period'), on: { change: function () { state.period = per.value; root.APP.route(); } } });
      [['this_month', t('app.this_month')], ['this_quarter', t('app.this_quarter')], ['this_year', t('app.this_year')], ['last_90', t('app.last_90')], ['custom', t('app.custom_range')], ['', t('app.all')]].forEach(function (p) { per.appendChild(h('option', { value: p[0], selected: p[0] === state.period }, p[1])); });
      var fromI = h('input', { type: 'date', class: 'inp', value: state.from, 'aria-label': t('app.from'), on: { change: function () { state.from = fromI.value; if (state.period === 'custom') root.APP.route(); } } });
      var toI = h('input', { type: 'date', class: 'inp', value: state.to, 'aria-label': t('app.to'), on: { change: function () { state.to = toI.value; if (state.period === 'custom') root.APP.route(); } } });
      main.appendChild(h('div', { class: 'filters' }, h('span', { class: 'small muted' }, t('app.period')), per, state.period === 'custom' ? fromI : null, state.period === 'custom' ? toI : null, h('span', { class: 'small muted' }, t('rp.period_hint'))));
      function money(v, short) { return canCom ? (short ? U.fmtMoneyShort(v, S.lang).replace(/ ?(SAR|ر\.س) ?/, '') : S.money(v)) : U.fmtNum(v); }
      function exportBtn(name, cols, rows) { return UI.exportButton({ module: 'reports', label: t('rp.export_report'), filename: 'report_' + name, rows: function () { return rows; }, columns: function () { return cols; } }); }
      function drillOpps(title, rows) { UI.drill(title, [{ key: 'name', label: t('app.opportunity'), width: 3, get: function (o) { return h('span', null, UI.recordLink('opportunity', o.id, MODEL.displayName('opportunity', o, S.lang)), h('span', { class: 'sub' }, S.customerName(o.customer_id))); } }, { key: 'stage', label: t('app.stage'), width: 2, get: function (o) { return UI.stageChip(o.stage, 'sm'); } }, { key: 'v', label: t('app.value'), width: 1.2, num: true, get: function (o) { return o._masked ? UI.lockNote() : UI.money(o.estimated_value, true); } }, { key: 'owner', label: t('app.owner'), width: 1.3, get: function (o) { return S.userName(o.owner_id); } }], rows, { onRow: function (o) { location.hash = '#/opportunities/' + o.id; } }); }
      var grid = h('div', { class: 'grid c2', style: { marginTop: '10px' } });

      /* 1 المسار حسب المرحلة */
      var byStage = R.pipelineByStage(db);
      grid.appendChild(UI.card({ title: t('rp.pipeline_stage'), sub: t('ov.def.pipeline'), actions: exportBtn('pipeline_stage', [{ key: 'label', label: t('app.stage'), get: function (r) { return S.lang === 'en' ? r.label_en : r.label_ar; } }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }, { key: 'weighted', label: t('rp.weighted') }], byStage), body: UI.hbars({ rows: byStage.filter(function (s) { return s.count; }).map(function (s) { return { label: (S.lang === 'en' ? s.label_en : s.label_ar), value: canCom ? s.value : s.count, color: STAGES.get(s.key).color === 'warn' ? 'warn' : (STAGES.get(s.key).color === 'accent' ? 'accent' : ''), onClick: function () { drillOpps(S.lang === 'en' ? s.label_en : s.label_ar, s.items); } }; }), format: function (v, r) { var s = byStage.find(function (x) { return (S.lang === 'en' ? x.label_en : x.label_ar) === r.label; }); return canCom ? money(v, true) + ' · ' + s.count : String(v); } }) }));
      /* 2 حسب العميل */
      var byCust = R.pipelineBy(db, 'customer_id', S.customerName).slice(0, 10);
      grid.appendChild(UI.card({ title: t('rp.pipeline_customer'), sub: S.lang === 'en' ? 'Top 10 by active pipeline value' : 'أعلى 10 عملاء بقيمة المسار النشط', actions: exportBtn('pipeline_customer', [{ key: 'label', label: t('app.customer') }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }, { key: 'weighted', label: t('rp.weighted') }], byCust), body: UI.hbars({ rows: byCust.map(function (r) { return { label: r.label, value: canCom ? r.value : r.count, onClick: function () { location.hash = '#/customers/' + r.key; } }; }), format: function (v) { return canCom ? money(v, true) : String(v); } }) }));
      /* 3 حسب القطاع */
      var bySec = R.pipelineBy(db, 'sector', function (k) { return S.label('sectors', k); });
      grid.appendChild(UI.card({ title: t('rp.pipeline_sector'), actions: exportBtn('pipeline_sector', [{ key: 'label', label: t('op.sector') }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }, { key: 'weighted', label: t('rp.weighted') }], bySec), body: UI.hbars({ rows: bySec.map(function (r) { return { label: r.label, value: canCom ? r.value : r.count, color: 'accent', onClick: function () { drillOpps(r.label, r.items); } }; }), format: function (v) { return canCom ? money(v, true) : String(v); } }) }));
      /* 4 حسب الموظف */
      var byOwner = R.pipelineBy(db, 'owner_id', function (k) { return k === '_none' ? '—' : S.userName(k); });
      grid.appendChild(UI.card({ title: t('rp.pipeline_owner'), actions: exportBtn('pipeline_owner', [{ key: 'label', label: t('app.owner') }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }, { key: 'weighted', label: t('rp.weighted') }], byOwner), body: UI.hbars({ rows: byOwner.map(function (r) { return { label: r.label, value: canCom ? r.value : r.count, onClick: function () { drillOpps(r.label, r.items); } }; }), format: function (v, r) { var x = byOwner.find(function (y) { return y.label === r.label; }); return (canCom ? money(v, true) : String(v)) + ' · ' + x.count; } }) }));
      /* 5 حسب المنطقة */
      var byReg = R.opportunitiesByRegion(db);
      grid.appendChild(UI.card({ title: t('rp.opps_region'), actions: exportBtn('by_region', [{ key: 'label', label: t('cu.region') }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }], byReg), body: UI.hbars({ rows: byReg.map(function (r) { return { label: r.label, value: r.count, color: 'ok', onClick: function () { drillOpps(r.label, r.items); } }; }), format: function (v, r) { var x = byReg.find(function (y) { return y.label === r.label; }); return v + (canCom ? ' · ' + money(x.value, true) : ''); } }) }));
      /* 6 الترسيات المتوقعة */
      var aw = R.expectedAwards(db, 12);
      grid.appendChild(UI.card({ title: t('rp.expected_awards'), sub: S.lang === 'en' ? 'Next 12 months by expected award date (weighted value when permitted)' : 'الأشهر الـ12 القادمة حسب تاريخ الترسية المتوقع (القيمة المرجحة عند السماح)', actions: exportBtn('expected_awards', [{ key: 'month', label: t('rp.month') }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }, { key: 'weighted', label: t('rp.weighted') }], aw), body: UI.barChart({ data: aw.map(function (a) { return { label: U.monthName(+a.month.split('-')[1] - 1, S.lang), value: canCom ? a.weighted : a.count, sub: String(a.count), color: 'accent', onClick: function () { drillOpps(U.fmtMonth(a.month, S.lang), a.items); } }; }), height: 220, format: canCom ? function (v, short) { return short ? money(v, true) : S.money(v); } : null }) }));
      /* 7 متوسط الوقت في كل مرحلة */
      var sd = R.stageDurations(db).filter(function (x) { return x.samples; });
      grid.appendChild(UI.card({ title: t('rp.stage_time'), sub: t('rp.def.stage_time'), actions: exportBtn('stage_time', [{ key: 'label', label: t('app.stage'), get: function (r) { return S.lang === 'en' ? r.label_en : r.label_ar; } }, { key: 'samples', label: t('rp.count') }, { key: 'avg', label: t('app.days') }, { key: 'threshold', label: 'max' }], sd), tight: true, body: UI.table({ columns: [{ key: 'label', label: t('app.stage'), width: 2.2, get: function (r) { return S.lang === 'en' ? r.label_en : r.label_ar; } }, { key: 'samples', label: t('rp.count'), width: .8, num: true }, { key: 'avg', label: t('app.days'), width: 1, num: true, get: function (r) { return h('span', { class: r.threshold && r.avg > r.threshold ? 'bold' : '' }, String(r.avg)); } }, { key: 'threshold', label: S.lang === 'en' ? 'Threshold' : 'العتبة', width: .9, num: true, get: function (r) { return r.threshold ? String(r.threshold) : '—'; } }, { key: 'bar', label: '', width: 2, get: function (r) { return h('div', { class: 'progress ' + (r.threshold && r.avg > r.threshold ? 'danger' : 'ok') }, h('i', { style: { width: Math.min(100, (r.avg / Math.max(1, r.threshold || r.avg)) * 100).toFixed(0) + '%' } })); } }], rows: sd }) }));
      /* 8 زمن إعداد العروض */
      var ta = R.proposalTurnaround(db, range);
      grid.appendChild(UI.card({ title: t('rp.proposal_turnaround'), sub: t('rp.def.turnaround'), body: h('div', { class: 'kpis c4' }, UI.kpi({ label: t('rp.count'), value: String(ta.count) }), UI.kpi({ label: S.lang === 'en' ? 'Average (days)' : 'المتوسط (يوم)', value: ta.avg === null ? '—' : String(ta.avg) }), UI.kpi({ label: S.lang === 'en' ? 'Max (days)' : 'الأقصى (يوم)', value: ta.max === null ? '—' : String(ta.max) }), UI.kpi({ label: S.lang === 'en' ? 'On-time rate' : 'نسبة الالتزام بالموعد', value: ta.on_time_rate === null ? '—' : U.pct(ta.on_time_rate), tone: 'ok' })) }));
      /* 9 الفوز والخسارة */
      var wl = R.winLoss(db, range);
      grid.appendChild(UI.card({ title: t('rp.win_loss'), sub: t('ov.def.win_rate'), body: h('div', null, UI.donut({ slices: [{ label: t('rp.won'), value: wl.won, color: 'var(--ok)' }, { label: t('rp.lost'), value: wl.lost, color: 'var(--danger)' }, { label: S.label('outcomes', 'cancelled'), value: wl.cancelled, color: 'var(--slate)' }].filter(function (s) { return s.value; }), center: wl.rate === null ? '—' : U.pct(wl.rate) }), canCom ? h('div', { class: 'stat-inline', style: { marginTop: '10px' } }, h('span', null, t('rp.won') + ' ', h('b', null, S.moneyShort(wl.won_value))), h('span', null, t('rp.lost') + ' ', h('b', null, S.moneyShort(wl.lost_value)))) : null), actions: h('button', { class: 'btn sm', type: 'button', on: { click: function () { drillOpps(t('rp.win_loss'), wl.won_items.concat(wl.lost_items)); } } }, t('app.details')) }));
      /* 10 أسباب الخسارة */
      var lr = R.lossReasons(db, range);
      grid.appendChild(UI.card({ title: t('rp.loss_reasons'), actions: exportBtn('loss_reasons', [{ key: 'key', label: t('op.loss_reason'), get: function (r) { return S.label('loss_reasons', r.key); } }, { key: 'count', label: t('rp.count') }, { key: 'value', label: t('rp.value') }], lr), body: UI.hbars({ rows: lr.map(function (r) { return { label: S.label('loss_reasons', r.key), value: r.count, color: 'danger', onClick: function () { drillOpps(S.label('loss_reasons', r.key), r.items); } }; }), format: function (v, r) { var x = lr.find(function (y) { return S.label('loss_reasons', y.key) === r.label; }); return v + (canCom ? ' · ' + money(x.value, true) : ''); } }) }));
      /* 11 المصادر */
      var src = R.sourcesWon(db, range);
      grid.appendChild(UI.card({ title: t('rp.sources'), actions: exportBtn('sources', [{ key: 'key', label: t('op.source'), get: function (r) { return S.label('opportunity_sources', r.key); } }, { key: 'total', label: t('rp.count') }, { key: 'won', label: t('rp.won') }, { key: 'rate', label: t('rp.rate') }], src), tight: true, body: UI.table({ columns: [{ key: 'key', label: t('op.source'), width: 2, get: function (r) { return S.label('opportunity_sources', r.key); } }, { key: 'total', label: t('rp.count'), width: .8, num: true }, { key: 'won', label: t('rp.won'), width: .8, num: true }, { key: 'rate', label: t('rp.rate'), width: .9, num: true, get: function (r) { return r.rate === null ? '—' : U.pct(r.rate); } }, { key: 'won_value', label: t('rp.value'), width: 1.2, num: true, get: function (r) { return canCom ? money(r.won_value, true) : '—'; } }], rows: src }) }));
      /* 12 اتجاه المتابعات المتأخرة */
      var ot = R.overdueTrend(db, 8);
      grid.appendChild(UI.card({ title: t('rp.overdue_trend'), sub: S.lang === 'en' ? 'Open overdue activities at the end of each week (last 8 weeks)' : 'الأنشطة المتأخرة المفتوحة في نهاية كل أسبوع (آخر 8 أسابيع)', body: UI.lineChart({ points: ot.map(function (w) { return { label: U.fmtDate(w.week_end, S.lang).split(' ').slice(0, 2).join(' '), value: w.count }; }), height: 200 }) }));
      /* 13 عملاء بلا نشاط */
      var inact = R.inactiveCustomers(db, root.RULES.hygiene.customer_no_interaction_days);
      grid.appendChild(UI.card({ title: t('rp.inactive_customers'), sub: (S.lang === 'en' ? 'No interaction for more than ' : 'بلا تفاعل لأكثر من ') + root.RULES.hygiene.customer_no_interaction_days + ' ' + t('app.days'), actions: exportBtn('inactive_customers', [{ key: 'name', label: t('app.customer'), get: function (r) { return MODEL.displayName('customer', r.customer, S.lang); } }, { key: 'last', label: t('cu.last_interaction') }, { key: 'days', label: t('rp.days_since') }], inact), tight: true, body: UI.table({ columns: [{ key: 'name', label: t('app.customer'), width: 2.5, get: function (r) { return UI.recordLink('customer', r.customer.id, MODEL.displayName('customer', r.customer, S.lang)); } }, { key: 'owner', label: t('cu.owner'), width: 1.3, get: function (r) { return S.userName(r.customer.owner_id); } }, { key: 'last', label: t('cu.last_interaction'), width: 1.2, get: function (r) { return r.last ? S.date(r.last) : '—'; } }, { key: 'days', label: t('rp.days_since'), width: 1, num: true, get: function (r) { return String(r.days); } }], rows: inact.slice(0, 15), onRow: function (r) { location.hash = '#/customers/' + r.customer.id; } }) }));
      /* 14 التحويلات والتكرار */
      var rr = R.repeatCustomerRate(db), cp = R.conversionProspectToOpp(db), ca = R.conversionProposalToAward(db, range);
      var convCard = UI.card({ title: t('rp.conv_prospect') + ' · ' + t('rp.conv_proposal') + ' · ' + t('rp.repeat_rate'), body: h('div', { class: 'kpis c3' }, UI.kpi({ label: t('rp.conv_prospect'), value: cp.rate === null ? '—' : U.pct(cp.rate), sub: cp.with_opportunity + ' / ' + cp.prospects, info: t('rp.def.conv_prospect') }), UI.kpi({ label: t('rp.conv_proposal'), value: ca.rate === null ? '—' : U.pct(ca.rate), sub: ca.won + ' / ' + ca.closed, info: t('rp.def.conv_proposal') }), UI.kpi({ label: t('rp.repeat_rate'), value: rr.rate === null ? '—' : U.pct(rr.rate), sub: rr.repeat_customers + ' / ' + rr.customers_with_contract, info: t('rp.def.repeat') })) });
      convCard.style.gridColumn = '1 / -1'; grid.appendChild(convCard);
      main.appendChild(grid);
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
